# Generated by Django 2.0.2 on 2018-04-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoc', '0003_auto_20180405_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='drivers',
            field=models.ManyToManyField(blank=True, help_text='Users who have committed to driving', related_name='drivers', to='umoc.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_paid',
            field=models.DateField(blank=True, help_text='Date the last time the user paid (blank if never)', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='num_seats',
            field=models.PositiveSmallIntegerField(help_text='Enter number of seats available for the trip', verbose_name='Total Trip Capacity'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Select users who are signed up to go on the trip', to='umoc.UserProfile'),
        ),
    ]
