# Generated by Django 2.0.2 on 2018-04-17 21:55

import django.core.validators
from django.db import migrations, models
import umoc.models


class Migration(migrations.Migration):

    dependencies = [
        ('umoc', '0005_auto_20180415_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, help_text='Enter your birth date in the format "YYYY-MM-DD"', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_num',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits and entered in the format '##########'.", regex='\\d{10}')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=umoc.models.profile_directory_path, verbose_name='Profile Image'),
        ),
    ]
