# Generated by Django 2.0.2 on 2018-04-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoc', '0007_auto_20180417_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='blank@blank.com', help_text="The user's email address", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(help_text='Enter Trip Name', max_length=40),
        ),
    ]
