# Generated by Django 2.0.2 on 2018-04-30 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoc', '0008_auto_20180423_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='tag',
            field=models.CharField(blank=True, choices=[('r', 'Rock Climbing'), ('h', 'Hiking'), ('s', 'Ski and Board'), ('sk', 'Skiing'), ('sn', 'Snowboarding'), ('c', 'Cabin Trip'), ('b', 'Biking')], help_text='Select a tag to help classify this trip', max_length=2),
        ),
    ]
