# Generated by Django 2.0.2 on 2018-04-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoc', '0004_auto_20180411_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=10, help_text='Enter number of seats available for the trip', verbose_name='Total Trip Capacity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='num_seats',
            field=models.PositiveSmallIntegerField(help_text='Enter number of seats available for the trip', verbose_name='Number of seats remaining'),
        ),
    ]
