# Generated by Django 2.0.2 on 2018-04-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umoc', '0006_auto_20180417_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, help_text='Enter your birth date in the format "YYYY-MM-DD"', null=True, verbose_name='Date of Birth'),
        ),
    ]
